config/routes.rb
Rails.application.routes.draw do
  resources :frameworks, only: [:index, :show, :new, :create]
  
  root to: 'frameworks#index'
end

app/models/framework.rb
class Framework < ActiveRecord::Base
  has_many :items
  
  accepts_nested_attributes_for :items
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :framework
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/frameworks_controller.rb
class FrameworksController < ApplicationController
  def index
    @frameworks = Framework.all
  end
  
  def show
    @framework = Framework.find(params[:id])
  end
  
  def new
    @new_framework = Framework.new
    5.times { @new_framework.items << Item.new(framework: @new_framework) }
  end
  
  def create
    framework = Framework.new(framework_params)
    framework.items.delete {Item.new}
    if framework.save
      redirect_to framework
    else
      redirect_to :index
    end
  end
  
  
  private
  
  def framework_params
    params.require(:framework).permit(:id, :name, :description, :items, :author, :link_to_original)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/frameworks_helper.rb
module FrameworksHelper
end

app/views/frameworks/_form.html.erb
<%= form_for framework do |f| %>
  Framework <%= f.label :name %>: <%= f.text_field :name %>
  <br>
  Framework <%= f.label :description %>: <%= f.text_area :description, rows: 1, cols: 100 %>
  <br>
    
  <% framework.items.each do |item| %>
    <br>
    <%= fields_for :items, item do |itemf| %>
      Item <%= itemf.label :name %>: <%= itemf.text_field :name %>
      <%= itemf.label :explanation %>: <%= itemf.text_area :explanation, rows: 1, cols: 100 %>    
    <% end %>
    <br>
  <% end %>
  <br>
    
  Framework <%= f.label :author %>: <%= f.text_field :author %>
  <br>  
  Framework <%= f.label :link_to_original %>: <%= f.url_field :link_to_original %>
  <br><br>
    
  <%= f.submit %>
<% end %>

app/views/frameworks/index.html.erb
<ul>
  <% @frameworks.each do |framework| %>
    <li>
      <%= link_to "#{framework.name}: #{framework.description}", framework %>
    </li>
  <% end %>
</ul>


<br><br>

<%= link_to 'Add a Framework', new_framework_path %>

app/views/frameworks/new.html.erb
<%= render partial: 'form', locals: {framework: @new_framework} %>

app/views/frameworks/show.html.erb
<%= @framework.name %>
<br>
<%= @framework.description %>

<ul>
  <% @framework.items.each do |item| %>
    <li><%= item.name %> <br> <%= item.explanation %></li>
  <% end %>
</ul>

<% @framework.items.each do |item| %>
  <%= form_for :item do |f| %>
    <%= f.label item.name %>
    <%= f.text_area :name, cols: 100, rows: 1 %>
  <% end %>
  <br>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Usethisframework</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>